# Generated by Django 4.2 on 2026-04-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0, max_length=10),
        ),
    ]
